name: 🚀 publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test_and_publish:
    uses: ./.github/workflows/publish.yml
    with:
      # so easy to forget bumping the version to match the tag, just override it!
      version: ${{ github.ref_name }}
    secrets:
      twine_username: ${{ secrets.PYPI_USERNAME }}
      twine_password: ${{ secrets.PYPI_TOKEN }}

  build_image:
    # TODO: remove this entire job if an image does not make sense (ie: just a library, no CLI)
    permissions: write-all
    needs: test_and_publish
    name: release image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Build and push image - release
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: ghcr.io/${{ github.repository }}:latest-build-cache
          cache-to: ghcr.io/${{ github.repository }}:latest-build-cache
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest

      - name: Show summary
        run: |
          echo 'Published:  ' >> ${GITHUB_STEP_SUMMARY}
          echo '* `ghcr.io/${{ github.repository }}:${{ github.ref_name }}`' >> ${GITHUB_STEP_SUMMARY}
          echo '* `ghcr.io/${{ github.repository }}:latest`' >> ${GITHUB_STEP_SUMMARY}
