name: 🧪 tests

on:
  workflow_call:
  push:
    branches-ignore:
      # these are already tested by publish-dev
      - dev
      - dev/*
      - dev-*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv requirements --dev > reqs.txt
          pip install -r reqs.txt

      - name: Lint check
        id: lint-check
        # allow unit tests to run even if this fails
        continue-on-error: true
        run: |
          make lint-check

      - name: Run unit tests
        run: |
          make test
      
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Final check
        if: ${{ steps.lint-check.outcome == 'failure' }}
        run: |
          echo Lint check failed, check its log
          exit 1
